version: "3"

services:
  db:
    container_name: pocket-usos-database
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - pocket-usos

  adminer:
    container_name: pocket-usos-adminer
    image: adminer
    restart: always
    ports:
      - 8880:8080
    networks:
      - pocket-usos

volumes:
  database_data:

networks:
  pocket-usos:
    name: pocket-usos
